service: zeitung

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  index:
    handler: dist/index.handler
    events:
    - eventBridge:
          schedule: cron(0 6 * * ? *)
          input:
            eventType: daily

    # only for testing
    #- http:
    #    cors: true
    #    path: '/'
    #    method: any
    #- http:
    #    cors: true
    #    path: '{proxy+}'
    #    method: any
